### ISSUE TITLE
 Adfc-Intern: Performance verbessern

### ISSUE THREAD

**Issue by JanBartels** [ADFC-Hamburg/adfc-ansible#100]
https://community.jitsi.org/t/how-to-to-setup-integrated-jitsi-and-jibri-for-dummies-my-comprehensive-tutorial-for-the-beginner/35718

https://github.com/jitsi/jitsi-videobridge/blob/master/config/20-jvb-udp-buffers.conf

**Comment by JanBartels** [comment]
Welche Videobridge ist aktuell installiert? JVB oder JVB2?

https://www.linux-magazin.de/news/jitsi-videobridge2-gilt-als-stabil/

**Comment by JanBartels** [comment]
https://www.kuketz-blog.de/jitsi-meet-optimierung-der-performance/

**Comment by tabacha** [comment]
> Welche Videobridge ist aktuell installiert? JVB oder JVB2?
> 
> https://www.linux-magazin.de/news/jitsi-videobridge2-gilt-als-stabil/

Jvb2

**Comment by tabacha** [comment]
> https://community.jitsi.org/t/how-to-to-setup-integrated-jitsi-and-jibri-for-dummies-my-comprehensive-tutorial-for-the-beginner/35718
> 
> https://github.com/jitsi/jitsi-videobridge/blob/master/config/20-jvb-udp-buffers.conf

Die Netzwerk-Performance-Werte sind auf dem Proxmox01 gesetzt, da der Rest Container ist.

Wir nutzen Ansible um alles aufzusetzen, und die Ansible Rolle: 

https://github.com/UdelaRInterior/ansible-role-jitsi-meet

für die wir schon ein paar Pull Request gemacht haben:

* https://github.com/UdelaRInterior/ansible-role-jitsi-meet/pull/10
* https://github.com/UdelaRInterior/ansible-role-jitsi-meet/pull/11
* https://github.com/UdelaRInterior/ansible-role-jitsi-meet/pull/12

Wahtscheinlich müssen wir weitere Pull-Requests machen

Unsere Config kann man im Live-System unter:

https://meet.adfc-intern.de/config.js

und im Testsystem unter:

https://test.adfc-intern.de/config.js

ansehen.

**Comment by tabacha** [comment]
warte auf https://github.com/UdelaRInterior/ansible-role-jitsi-meet/pull/14 um dann noch an den Dingen die auf kuketz-blog genannt werden zu drehen. Wobei ich: disableAudioLevels so lassen würde (false) ist schon praktisch, wenn man mehrere Mikrofone hat, wenn man sehen kann ob ich rede / auch praktisch wenn man ein Defekten Kopfhörer hat und sehen kann, wenn jemand anderes redet

**Comment by JanBartels** [comment]
In https://community.jitsi.org/t/reducing-resource-usage-to-improve-performance-both-client-side-and-server-side/39891 werden einige Maßnahmen zur Performanceverbesserung empfohlen. Eine sehr erfolgreiche scheint die Nutzung von HW-beschleunigten Cryptoverfahren zu sein. Tests siehe
https://www.cyberciti.biz/faq/how-to-find-out-aes-ni-advanced-encryption-enabled-on-linux-system/

Auf meet.adfc-intern.de sehe ich eine Abweichung (es sollen beide Zahlen gleich sein):

> root@meet:~ # lscpu|grep '^CPU(s):'
> CPU(s):              12
> root@meet:~ # grep -o aes /proc/cpuinfo|wc -l
> 9

Auf proxmox01 sind in beiden Fällen 12 CPUs gelistet. Weiterhin ergibt sich eine Abweichung bei openssl (sowohl auf proxmox01 als auch auf meet):

> root@proxmox01 ~ # openssl engine
> (dynamic) Dynamic engine loading support

Laut Blogbeitrag soll da bei Intel-CPUs stehen:

> $ openssl engine
> (aesni) Intel AES-NI engine
> (dynamic) Dynamic engine loading support

Bitte prüfen.

Außerdem wird dort empfohlen, DISABLE_VIDEO_BACKGROUND in der interface_config.js auf true zu setzen, um die Clients deutlich zu entlasten. Steht bei uns auf false.
