### ISSUE TITLE
portal.adfc-intern.de leitet nicht auf https um

### ISSUE THREAD

**Issue by JanBartels** [ADFC-Hamburg/adfc-ansible#106]
Wenn man portal.adfc-intern.de in der Browserzeile eingibt, wird http anstelle von https verwendet. Das ist doof, weil man auf dem Portal u. U. Passworte eingibt, die verschlüsselt übertragen werden müssen. Außerdem steht die Benutzerverwaltung mit personenbezogenen Daten hinter dieser URL. Da gebietet schon alleine die DSGVO die verschlüsselte Übertragung.

Bitte Umleitung einbauen.

**Comment by tabacha** [comment]
```
ucr set apache2/force_https=yes
systemctl restart apache2
```
Done
