### ISSUE TITLE
Verbindung zu Sipgate reicht manchmal ab.

### ISSUE THREAD

**Issue by tabacha** [ADFC-Hamburg/adfc-ansible#122]
Im Logfile finden sich folgende Meldungen:
```
[Aug 30 00:00:01] Asterisk 16.2.1~dfsg-1+deb10u1 built by nobody @ buildd.debian.org on a unknown running Linux on 2019-08-20 20:31:36 UTC
[Sep  5 12:21:25] WARNING[3733] res_pjsip_outbound_registration.c: No response received from 'sip:sipgate.de:5060' on registration attempt to 'sip:..@sipgate.de:5060', retrying in '20'
[Sep  5 12:22:17] WARNING[3733] res_pjsip_outbound_registration.c: No response received from 'sip:sipgate.de:5060' on registration attempt to 'sip:...@sipgate.de:5060', retrying in '20'
[Sep  5 12:23:09] WARNING[3733] res_pjsip_outbound_registration.c: No response received from 'sip:sipgate.de:5060' on registration attempt to 'sip:...@sipgate.de:5060', retrying in '20'
....
[Sep  5 12:43:11] WARNING[3733] res_pjsip_outbound_registration.c: No response received from 'sip:sipgate.de:5060' on registration attempt to 'sip:....@sipgate.de:5060', retrying in '20'
[Sep  5 12:44:03] WARNING[3733] res_pjsip_outbound_registration.c: Maximum retries reached when attempting outbound registration to 'sip:sipgate.de:5060' with client 'sip:...@sipgate.de:5060', stopping registration attempt
```

**Comment by GeorgSommer** [comment]
Könnte es daran liegen, dass wir den gleichen SIP-Account auch für den UCS.-Master verwenden, der darüber ja SMS verschickt für passwort-reset & co? Das passiert zwar nicht oft - aber vielleicht checkt UCS ja immer mal nach, ob er darauf auch Zugriff hat und dann kommen die beiden sich in Quere?

**Comment by tabacha** [comment]
> Könnte es daran liegen, dass wir den gleichen SIP-Account auch für den UCS.-Master verwenden, der darüber ja SMS verschickt für passwort-reset & co? Das passiert zwar nicht oft - aber vielleicht checkt UCS ja immer mal nach, ob er darauf auch Zugriff hat und dann kommen die beiden sich in Quere?

Nein, schließe ich aus, das sind unterschiedliche APIs, das SMS verschicken hat nichts mit dem Rest zu tun. Die Logmeldungen geben ja schon hinweis: Es gibt keinen Response von sipagte.de

**Comment by tabacha** [comment]
Wir brauchen halt etwas, was die Asterisk Verbindung neu startet, wenn er keine Verbindung hat. Dazu brauche ich einmal die Fehlersituation in Live, damit ich das Skripten kann. Also bitte anrufen, wenn du die Situation bemerkst.
