### ISSUE TITLE
Option userDocumentationURL aktivieren

### ISSUE THREAD

**Issue by JanBartels** [ADFC-Hamburg/adfc-ansible#162]
In der config.js für meet soll die Option userDocumentationURL aktiviert werden:

```
     deploymentUrls: {
    //    // If specified a 'Help' button will be displayed in the overflow menu with a link to the specified URL for
    //    // user documentation.
        userDocumentationURL: 'https://portal.adfc-intern.de/adfc/adfc-meet.pdf'
    //    // If specified a 'Download our apps' button will be displayed in the overflow menu with a link
    //    // to the specified URL for an app download page.
    //    downloadAppsUrl: 'https://docs.example.com/our-apps.html'
    },
```
Diese Option bewirkt, dass es im Menü einen Punkt "Hilfe" gibt, der das PDF mit der Anleitung öffnet. Weil die config.js über ansible verwaltet wird, stelle ich das Issue hier ein und nicht unter dem jitsi-meet-Repo. Auf dem Testserver habe ich das gerade testweise manuell in die config.js eingetragen.

**Comment by tabacha** [comment]
@JanBartels Hab das auf meet.adfc-intern.de deployed, sehe aber keinen Unterschied zu vorher, magst du das mal bitte prüfen.

Gruß + Frohes Fest
Sven

**Comment by JanBartels** [comment]
Funktioniert wie vorgesehen. Im Menü (vgl. Screenshot der bisherigen Version in Kap. 5 der Doku) ist nun unten ein Menüpunkt "Hilfe" neu, der die Doku öffnet.
