### ISSUE TITLE
rsync wird bei Aufruf Sync Theme folder (synchronise) nicht gefunden obwohl vorhanden

### ISSUE THREAD

**Issue by martinweil** [ADFC-Hamburg/adfc-ansible#47]
Bei Aufruf von ansible-playbook setup-client.yml hängt dieses immer recht weit hinten bei der Synchronisierung des Theme Folders mit der Meldung das rsync im Pfad nicht gefunden wurde:
![synchronise failed](https://user-images.githubusercontent.com/53993169/66505128-fb2f8680-eaca-11e9-8b05-512230d19d25.png)

rsync ist jedoch im Pfad /usr/bin/rsync enthalten und startet ebenfalls.
![which rsync](https://user-images.githubusercontent.com/53993169/66505129-fbc81d00-eaca-11e9-99fa-54ae6b7ef36b.png)

Es gab hierzu schon mal eine Diskussion bei ansible-semaphore, ich bin mir aber nicht sicher ob das etwas damit zu tun hat: https://github.com/ansible-semaphore/semaphore/issues/255

Kann den Fehler jemand nachvollziehen?

**Comment by tabacha** [comment]
Ich vermute, du bauchst das rsync auf deiner Maschine

**Comment by martinweil** [comment]
Daran lag es...
