### ISSUE TITLE
Adfc-Intern: Statistiken

### ISSUE THREAD

**Issue by tabacha** [ADFC-Hamburg/adfc-ansible#90]

**Comment by JanBartels** [comment]
Das Dashboard vom Freifunk München ist Grafana (kam mir sofort vertraut vor). Es gibt passende Plugins für Jitsi:

https://grafana.com/grafana/dashboards?direction=asc&orderBy=name&search=Jitsi

Man braucht dann noch eine InfluxDB und Telegraf zum Sammeln. Diese Tools kommen zusammen mit Grafana aus demselben Umfeld (TIG-Stack, also Telegraf, Influx und Grafana).

Installationsanleitung:

https://community.jitsi.org/t/how-to-to-setup-grafana-dashboards-to-monitor-jitsi-my-comprehensive-tutorial-for-the-beginner/38696

**Comment by tabacha** [comment]
Ja, das schwebt mir auch vor, brauche nur noch ein Ansible-Skript dafür und eine Entscheidung ob es auf den Proxmox oder auf den meet soll.

**Comment by tabacha** [comment]
Siehe #101 
Die Daten gehen gearde schon in die InfluxDB die Dashboards müssten noch gebaut werden.

**Comment by tabacha** [comment]
Moin,

Ich habe jetzt telegraf auf alle Maschinen aufgesetzt und die Daten gehen in eine InfluxDB.  Ein Grafana mit https (Nginx davor) gibt es auch schon.

Gibt es jemanden mit Grafana-Kenntnissen (oder Lust sich da einzuarbeiten) und ein paar Dufte Dashboards zu bauen.

Passwort gibt es per persönlicher E-Mail.

https://github.com/ADFC-Hamburg/adfc-ansible/issues/90

Gruß
Sven

**Comment by GeorgSommer** [comment]
ich schaue mir das Grafana auch mal an - keine Garantie, dass ich da etwas brauchbares zu Stande kriege, aber kucken und reversibel klicken schaffe ich.
