### ISSUE TITLE
Adfc-Intern: LDAP erweiterung

### ISSUE THREAD

**Issue by tabacha** [ADFC-Hamburg/adfc-ansible#93]
Besondere Attribute für Landesverband, Kreisverband Mitgliedsnummer etc.

Das für UCS benutzbar machen

**Comment by tabacha** [comment]
https://docs.software-univention.de/developer-reference-4.4.html

**Comment by GeorgSommer** [comment]
Jan hat angekündigt sich dazu zu melden

**Comment by JanBartels** [comment]
Für die LDAP-Erweiterungen können wir die ADFC-NRW PEN verwenden. 

OID-Präfix: 1.3.6.1.4.1.34127.2

Siehe
https://www.iana.org/assignments/enterprise-numbers/enterprise-numbers

**Comment by tabacha** [comment]
Perfekt

**Comment by JanBartels** [comment]
https://github.com/ADFC-Hamburg/adfc-ansible/issues/93#issue-606725933: 
> `Besondere Attribute für Landesverband, Kreisverband Mitgliedsnummer etc.`

Die Gliederungen können wir direkt auf die Standard-LDAP-OUs (organizationalunit) abbilden, die zugeordneten Personen auf die Klassen Person und InetOrgPerson. Mitgliedsnummer brauchen wir aus Gründen der Datensparsamkeit m. E. nicht. I. w. reichen uns nur Name, EMail-Adresse und Gliederungszugehörigkeit sowie die technischen Login-Daten. Die Mitgliedsnummer als Nachweis der Mitgliedschaft kann als organisatorische Maßnahme direkt beim Anlegen manuell überprüft werden und braucht deshalb nicht gespeichert werden. Wir können sie ohnehin nicht automatisiert prüfen oder in irgendeiner Weise sinnvoll verarbeiten.

Wir kommen folglich ohne LDAP-Schema-Erweiterungen aus.

**Comment by tabacha** [comment]
Ja, könnte man so machen, leider funktionier das Self-Service Plugin von UCS so nicht,  man kann nur Attribute zur bearbeitung/registrierung angeben, nicht die DN.

Deshalb fände ich das recht praktisch am Objekt.

**Comment by JanBartels** [comment]
Hilft uns das?

https://help.univention.com/t/organizing-users-in-organizational-units/8115/3

**Comment by tabacha** [comment]
Nein, das Self-Service Plugin speichert immer hier: ```cn=self registered users,dc=adfc-intern,dc=de```

Ich habe 20 Jahre Erfahrung mit UCS und bin mir sehr sicher, dass wir eine Schema-Erweiterung brauchen, wenn wir den LV erfassen wollen.

**Comment by tabacha** [comment]
Ich habe das mal kurz zusammengehäckt

https://github.com/ADFC-Hamburg/adfc-intern-ldap-extension


muss noch installiert werden und dann müssen wir uns Gedanken über die Abläufe machen. Soll da noch jemand die Benutzer freischalten? Was ist mit den LVs die sich im Moment nicht finanziell / personell beteiligen? @GeorgSommer
