### ISSUE TITLE
Adfc-Intern: Startseite Designen

### ISSUE THREAD

**Issue by tabacha** [ADFC-Hamburg/adfc-ansible#94]
Kenntnise: HTML/Js

Am besten gleich Jitis -Meet einbinden 

npm install jitsi-meet

**Comment by JanBartels** [comment]
https://github.com/jitsi/jitsi-meet/blob/master/config.js:

disableAudioLevels: true,
(siehe https://community.jitsi.org/t/customizing-jitsi-viewer-only-bandwidth-usecase/32457/9)

defaultLanguage: 'de',

Patch für Chrome als bevorzugten Browser:
https://github.com/jitsi/jitsi-meet/pull/5639/files

**Comment by tabacha** [comment]
Ja, das ist die "sanfte Art"  eine andere Möglichkeit wäre die Startseite kommplett neu zu designen, denn alles was jitsi-meet angeht ist in ``npm install jitsi-meet`` enthalten

**Comment by JanBartels** [comment]
Das mit dem Zusammenbauen der React-Applikation ist mir schon klar. Es ging mir mehr um die Optionen, um die wir uns kümmern müssen. Lass uns erst mal die config.js direkt patchen und die Applikation bauen, wenn wir wissen, was wir brauchen und was wir wollen.

**Comment by tabacha** [comment]
Auf https://test.adfc-intern.de/ ist schon ein Foot eingebaut.

**Comment by JanBartels** [comment]
Oberfläche im ADFC-CD ist eingecheckt. Bitte bauen und deployen.

**Comment by JanBartels** [comment]
Merge von jitsi.org

**Comment by tabacha** [comment]
Die Änderungen direkt in master einzuchecken ist etwas suboptimal.

Hab mal einen Pull-Request erstellt, damit man deine Änderungen sehen kann:

https://github.com/ADFC-Hamburg/jitsi-meet/pull/1/files

Ich weiß noch nicht wie wir das am besten deployen. z.B ist jetzt das Debian Paket: Mit der Versionsnummer: 1.0.4074-1 dort. Das ist ja nicht master, sondern dieser Tag:

https://github.com/ADFC-Hamburg/jitsi-meet/releases/tag/4074

Evtl ist auf dem Master ja auch noch ein Bug oder sowas und wir müssen dann immer die Änderungen analog zu dem Paket bauen.

Sorry ich will einen sauberen Prozess haben, der ist mir wichtiger als das die Seite hübsch aussieht.
