### ISSUE TITLE
Adfc-Intern: Namenseingabe bei Jitsi-Aufruf erzwingen

### ISSUE THREAD

**Issue by theraser** [ADFC-Hamburg/adfc-ansible#98]
Jitsi bietet die Möglichkeit per Eingabefeld schon vor dem Beitreten einer Sitzung die Eingabe eines Namens zu erzwingen, sofern er nicht schon per Cookie vom letzten Mal gespeichert ist. Das erleichtert die Kommunikation extrem, weil nicht bei jeder Sitzung wieder erklärt werden muss, wo und wie man den eigenen Namen festlegt.

Dazu muss die Option "requireDisplayName" auf True gesetzt werden.

Siehe dazu: https://github.com/jitsi/jitsi-meet/blob/master/config.js#L253

**Comment by tabacha** [comment]
In https://meet.adfc-intern.de/config.js ist die Variable auf true. Müsste untersucht werden, warum das nicht greift.

**Comment by theraser** [comment]
Danke für den Hinweis, jetzt scheint es hier auch zu greifen. Vielleicht war es einfach nur ein fehlender Neustart in den letzten Tagen :-)
